package ch07;


/*
class MyException extends Throwable{
    public MyException(String s) {
        super (s);
    }
}
public class Exception {
    public Exception(String g里面的异常) {
    }

    public static void main(String[] args) {
        try {if(args.length >0)

            throw new MyException("xxx");
            System.out.println("hello");


        } */
/*catch (MyException e) {
          *//*
*/
/*  e.printStackTrace();*//*
*/
/*
        }*//*

        catch (Throwable t){
            System.out.println("catch....");

        }
        finally {
            System.out.println("finally");
        }

    }

}
*/
